name: Compile with nuitka linux

on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/setup-python@v5
      with:
          python-version: '3.11'
          cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install Pillow numpy mss aiohttp pynput nuitka
        echo "Finished installing dependencies"
    
    - name: nuitka setup
      run: |
        echo "NUITKA_CACHE_DIR=${{ github.action_path }}/nuitka/cache" >> $GITHUB_ENV


  
    - name: Install ccache
      run: |
        sudo apt-get install -y ccache

    
    - name: Compile
      run: |
        python -m nuitka --standalone --onefile --show-progress --remove-output main.py
      working-directory:
        .
